# Generated by Django 2.2.4 on 2020-10-18 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placar1', models.IntegerField(default=0, help_text='Indica o total de golos da 1ª equipe', verbose_name='Placar 1')),
                ('placar2', models.IntegerField(default=0, help_text='Indica o total de golos da 2ª equipe', verbose_name='Placar 2')),
                ('valor', models.DecimalField(decimal_places=2, default=5, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premio', models.DecimalField(decimal_places=2, default=5, max_digits=11)),
                ('data_criada', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('aposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vencedores', to='blog.Aposta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victorias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placar1', models.IntegerField(default=0, help_text='Indica o total de golos da 1ª equipe', verbose_name='Placar 1')),
                ('placar2', models.IntegerField(default=0, help_text='Indica o total de golos da 2ª equipe', verbose_name='Placar 2')),
                ('data_criada', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_partida', models.DateTimeField(default=None, verbose_name='Data da partida')),
                ('concluido', models.BooleanField(default=False)),
                ('equipe1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe1', to='blog.Equipe', verbose_name='1ª Equipe')),
                ('equipe2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe2', to='blog.Equipe', verbose_name='2ª Equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=10, max_digits=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='aposta',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apostas', to='blog.Partida'),
        ),
        migrations.AddField(
            model_name='aposta',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apostas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='aposta',
            unique_together={('user', 'partida')},
        ),
    ]
