# Generated by Django 2.2.4 on 2020-10-18 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aposta',
            name='concluido',
            field=models.BooleanField(default=False, help_text='Indica se os jogadores ja receberam os prêmios'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='aposta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='blog.Aposta'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitorias', to=settings.AUTH_USER_MODEL),
        ),
    ]
