# Generated by Django 2.2.4 on 2020-10-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201018_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aposta',
            name='concluido',
        ),
        migrations.AddField(
            model_name='partida',
            name='encerrado',
            field=models.BooleanField(default=False, help_text='Indica se os jogadores ja receberam os prêmios'),
        ),
    ]
